### ISSUE TITLE
Question : Using jwalkable for 3D games 

### ISSUE THREAD

**Issue by Ali-RS** [implicit-invocation/jwalkable#1]
Hi 

Thanks for the library. 
I am developing a **3D game**. I am curious if I can use this library for path finding ? (I need to do path finding only in XoZ plane (2D Plane) the height (Y) will be calculated by physic system.)
In my case X=0,Y=0,Z=0 is world center.

based on the [wiki page](https://github.com/totologic/daedalus-lib/wiki/2.-Basic-tools-to-build-triangulations) from daedalus-lib

> Meshes implements coordinates space (x, y) with rules:
> 
>     top-left corner defines (0, 0) coordinates
>     bottom-right corner defines (width, height) coordinates
> 
> You should consider this rectangle as defining an AABB for your environment.

How should I construct **PathHelper** in my case ? Do I need to only write a simple transform function to transform position vector back and force between jWalkable and game engine ? 
like : 
From jWalkable TO game engine : (x,y) --> (x, -y) - (width/2, - Height/2) = (X,Z)
From game engine TO jWalkable : (X,Z) + (width/2,- Height/2) = (x,y) --> (x, -y)
ex : Height = 100 meters, Weight = 100 meters
From jWalkable TO game engine : (100,100) --> (100,-100) - (50, -50) = (50,-50) 
From game engine TO jWalkable : (50, -50) + (50, -50) = (100, -100) --> (100, 100)

Will appreciate your help
Regards

**Comment by implicit-invocation** [comment]
You just have to make sure (x, y) passed to jWalkable is in the range between (0, 0) and (width, height), your transform will work fine.

**Comment by Ali-RS** [comment]
Okay, thanks. 
Does this library also contain field of view in dynamic environment demo? 
https://www.youtube.com/watch?v=MfQkns4F6rU
