### ISSUE TITLE
Infinite loop in Geom2D

### ISSUE THREAD

**Issue by adam-law** [implicit-invocation/jwalkable#3]
I'm trying to use this with the Java SE Graphics2D geometry. I'm making progress getting it to work but there are times when no path is generated, even when the reverse motion (I'll explain below), generates a path.

For example, if I drag the object downward toward an obstacle and past it, it generates a path. But when I drag it back up and past the same object, back to the initial starting point, no path is generated.

Trying to be clever, I reverse the start and end points of the 2nd attempt, and then reverse the resultant float array, and voila, it yields a path! BUT, up to a degree, if I drag it too far up from the obstacle, it freezes. I couldn't properly trace the issue, but stepping through the code and looking at the lines here in your repo, it seems that the process is infinitely looping in Geom2D.locatePosition at the line 152 loop i.e. it never breaks out.

I guess there are 2 questions here:

1. How does one use this library properly for Java2D? I basically pass obstacles as polygons where I use a path iterator of an Area to capture its vertices. Then I pass the start and end points and radius of my object, and it's working about 70% to 80% of the time. The rest of the cases, no path is generated, unless I reverse the start and end points, and reverse the result.

2. Can a failsafe be put in to break out of the loop, especially when there are some points already generated? This can allow a dev to do path correction on his/her own code. Better yet, if there's a solution that fixes this without having to put corrective code on the user-end, then so much the better.

Thanks.

Edit: 3. Is it a mistake to just pass all my shapes as polygons and derive their vertices with the method I described above? The testing shapes I'm using are rectangles, for now, but I don't create the Obstructions with PathHelper.addRect(), I use PathHelper.addPolygon(vertices) for everything.

Edit 2: So I've downloaded the source and I'm reviewing it. I found the tmp1 variable that I think you used to break out of the loop. The issue remains that, generally, sometimes no path is generated or in the case of Geom2D, breaking out of an infinite loop means I get 

> hxDaedalus.data.math.Intersection objectContainer = hxDaedalus.data.math.Intersection.ENull

which causes failure at AStar.findPath because AStar.fromFace == null.

I'm not sure what's causing all this. Some insight would be helpful. Thanks.

**Comment by adam-law** [comment]
I was able to address most of the issues app-side. The break from the infinite loop was sufficient to figure out the other stuff. Closing the issue.

**Comment by implicit-invocation** [comment]
I didn't have the time to look at it and never ran into this kind of bug too.  
But there's something you can check quickly:
- are both the start and the end point inside the bound of the world?
- each entity has a radius, which makes them a circle, does that circle overlap with the bound or any obstacles?
- `PathHelper#addRect` calls to `PathHelper#addPolygon`, if you use `PathHelper#addPolygon` directly, you don't have to close the shape (no need to pass the starting point twice) and the order matters.

And if you found out the issues in your data, can you describe the case for other who can run into this bug?  
Thanks.

**Comment by adam-law** [comment]
Hi, I'm sorry I didn't see this sooner. Your comment might explain the new issue I opened regarding negative coordinates (i.e. outside world bounds). These values might be the "data issue" as well. I define the bounds using Integer.MAX_VALUE for both width and height, since I'm using an "infinite" canvas. Seeing that the constructor only accepts positive values (I think?), may be the cause of my issues.

Thanks for the answers!
