### ISSUE TITLE
hxDaedalus is licensed under MIT

### ISSUE THREAD

**Issue by nanjizal** [implicit-invocation/jwalkable#5]
Could you please amend the license to MIT and append these:
https://github.com/hxDaedalus/hxDaedalus/blob/master/LICENSE
https://github.com/azrafe7/hxPixels/blob/master/LICENSE
hxDaedalus, and hxPixels are MIT, not Apache2, we would prefer if you can keep it MIT and include these within your license.
Could you make it clearer that the active code is based on hxDaedalus based on Daedalus by amending the Readme in a suitable way and add these links.

https://github.com/hxDaedalus/hxDaedalus
https://github.com/azrafe7/hxPixels
https://github.com/hxDaedalus/hxDaedalus-swing-examples
https://github.com/totologic/daedalus-lib

Cool your making use of Daedalus but please make sure that you credit developer, and include relevant licenses, ideally please keep it as MIT.

Many Thanks all the best Justin

**Comment by implicit-invocation** [comment]
Done :)

**Comment by nanjizal** [comment]
By the way you might be curious 
https://nanjizal.github.io/TrilateralBazaar/hxDaedalusTest/binWebGL/
Bit heavy need to really look into optimising.
Thanks for changes :)
